#!/usr/bin/env python2
# pycor-cli
#    container/overlay, python version
#

import sys
import traceback

from pycor.loghandler import logger, logging, sh
from pycor.optparser import optargs


if __name__ == "__main__":

    # catch debug opt
    if optargs['--debug']:
        debug = True
        logger.setLevel(logging.DEBUG)
        sh.setLevel(logging.DEBUG)
    else:
        debug = False


    try:
        from pycor.dispatch import dispatch

        # dispatch function based on cli args
        dispatch(optargs['<action>'], optargs['<args>'])
        sys.exit(0)

    except Exception as e:
        logger.error(str(e))
        logger.debug(traceback.format_exc())
        sys.exit(1)
